# Generated by Django 3.0.3 on 2020-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='posts', max_length=255),
        ),
    ]
