# Generated by Django 3.0.3 on 2020-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_auto_20200714_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='this is snippet box', max_length=255),
        ),
    ]
